### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by wmayner** [0rpc/zerorpc-python#108]
This library looks awesome. Any chance of it being updated to work with Python 3? 

Happy to help if I can! :smiley:

**Comment by dvreed** [comment]
@wmayner, any update on that PR?  I'd love to be able to use this with python 3.

**Comment by eranimo** [comment]
+ 1. I also need this. What can be done to get this faster?

**Comment by alekibango** [comment]
Today, `python3 setup.py  install ` worked for me, which gave me hope...
But:
  `zerorpc`
still leads to error mentioned above:
```log
    import gevent_zmq as zmq
ImportError: No module named 'gevent_zmq'
```

**Comment by mehdisadeghi** [comment]
Have you tried this:

    import zmq.green as zmq

**Comment by alekibango** [comment]
@mehdisadeghi  thansk for this hint.
i tried that, edited few python files around... fixing zmq.green, exceptions, print statements, 
and result is this (runs, but does not work as expected):

```
zerorpc --server tcp://0.0.0.0:2345 time
connecting to "tcp://0.0.0.0:2345"
serving "time"
Traceback (most recent call last):
  File "/home/dp/test/zerorpc3/lib/python3.4/site-packages/gevent-1.1-py3.4-linux-x86_64.egg/gevent/greenlet.py", line 340, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/dp/test/zerorpc3/lib/python3.4/site-packages/zerorpc-0.4.4-py3.4.egg/zerorpc/events.py", line 55, in _sender
    for parts in self._send_queue:
TypeError: iter() returned non-iterator of type 'Channel'
<Greenlet at 0x7f764b2666d0: <bound method Sender._sender of <zerorpc.events.Sender object at 0x7f7646ec2e80>>> failed with TypeError
```
So, still not working, now i need to figure out how to make Channel work. [Here is my fork](https://github.com/alekibango/zerorpc-python), where i am trying to achieve python3 compatibility (not both, just py3 for now)

**Comment by bombela** [comment]
I did the same thing, trying to get py3 only first and got most test to
pass, but I had to modify gevent and it was few month ago. I will see if I
can take some time to upload all my updates but i highly doubt that it will
work.

**Comment by TDaltonC** [comment]
What about switching over to asynchIO? I'm sure that sounds extreme, and I don't know the details of how 0rpc is using gevent, but reading the years of almost-but-not-quite py3 compatibility [documented in on that repo](https://github.com/gevent/gevent/issues/38), I think that py3 support is not a priority for @denik and @fantix.

**Comment by bombela** [comment]
asyncio is really a good idea. It's probably the best way forward now that you mention it. This might require a new 'zerorpc-python-asyncio' package and a different repository altogether, but this is probably better than having a fork of gevent + bad interop with all asyncio libs of python>=3.4.

**Comment by alekibango** [comment]
Please do not forget to consider some limitations of [aiozmq](https://aiozmq.readthedocs.org/) (asyncio zeromq integration):
  -  You obviously cannot use ipc://name schema for endpoint
  -  aiozmq`s loop aiozmq.ZmqEventLoop is built on top of select system call, so it’s not fast comparing to asyncio.ProactorEventLoop and it doesn’t support subprocesses.

While we all can probably live without ipc://name schema, the second point is making me little nervous..

**Comment by bombela** [comment]
Aren't the limitation for MS Windows?

**Comment by TDaltonC** [comment]
Gevent is not python3 compatible.

https://github.com/gevent/gevent/issues/38#issuecomment-121001665

**Comment by mehdisadeghi** [comment]
The issue that you have mentioned is closed and now gevent works with with
python3. There is also an alpha release on pypi:
https://pypi.python.org/pypi/gevent/1.1a2.

**Comment by bombela** [comment]
That's sweet. Give me few weeks to get to some version of zerorpc for python3.  Ping me if I am taking things too slow.

**Comment by alekibango** [comment]
gevent3 py support is great news!

@bombella, oops -- i think you are right, those limitations might be for windows only. 
I would like to see some benchmarks comparing gevent and aiozmq though. I kind of like both of them -> will prolly need to find time to test them myself. i will report numbers here if they will be interesting.

**Comment by TDaltonC** [comment]
@bombela bump

**Comment by bombela** [comment]
and... shame on me because I've not progressed. I will busy again for the following 2 weeks :(

My plan was to update the code to work on both py3 and py2.6, via common syntax + the six library. Pull requests are welcome (hint hint ;)).

Hopefully the extensive test suite should help at the job.

**Comment by bombela** [comment]
see branch python3.4.

This branch will be merged into master as soon as all tests are passing. Thereafter it will go into a release candidate on pypi.

**Comment by stevenvanrossem** [comment]
I want to raise this related issue:
zerorpc seems not yet python version agnostic: an error occurs when server is started with python2 and client with python3 (tested with the hello world example from www.zerorpc.io)
`RuntimeError: Unable to find a pattern for: hello {b'message_id': b'ff84635edaa045e5b4a7a92d52bc8968', b'v': 3} ('RPC',)`

When both client and server are started from the same python version (2 or 3) then it works correctly. Anybody has an idea if zerorpc can be used with mixed python versions?

**Comment by bombela** [comment]
It should work and if not, It's a bug. It must be the same problem
preventing nodejs and zerorpc python3 from working together.

**Comment by shimondoodkin** [comment]
+1

**Comment by shimondoodkin** [comment]
what is missing?

seems build is passing but there are some stack traces. 
https://travis-ci.org/0rpc/zerorpc-python/jobs/135208127

can i use the 3.4 branch?

**Comment by bombela** [comment]
You can use the 3.4 branch. Stack traces are part of the tests.

**Comment by leftink** [comment]
@bombela Any update on when the python 3 version might make it into PyPi?  This is definitely something we are interested in using at our company, but IT has only approved getting packages from PyPI and won't let us pull from Git directly.

**Comment by bombela** [comment]
Working on it. Expect the python3 branch to be merged into master and the whole thing released to PyPi in the next few hours.

**Comment by bombela** [comment]
python3 compatible version released on PyPi: https://pypi.python.org/pypi/zerorpc

Enjoy.
