### ISSUE TITLE
Recover from error after return

### ISSUE THREAD

**Issue by grantjenks** [0rpc/zerorpc-python#114]
I wrote a simple message queue server using ZeroRPC:

```
import zerorpc
import argparse
from daemon import runner
from collections import deque

class Queue(object):
    def __init__(self):
        self._queue = deque()
    def get(self):
        return self._queue.popleft()
    def put(self, value):
        self._queue.append(value)
    def len(self):
        return len(self._queue)

class Application(object):
    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = self.stderr_path = args.logfile
        self.pidfile_path = args.pidfile
        self.pidfile_timeout = 5

    def run(self):
        server = zerorpc.Server(Queue())
        server.bind('tcp://{0}:{1}'.format(args.host, args.port))
        server.run()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('action')
    parser.add_argument('--pidfile', default='/tmp/queued.pid')
    parser.add_argument('--logfile', default='/tmp/queued.log')
    parser.add_argument('--host', default='127.0.0.1')
    parser.add_argument('--port', default='8080')
    args = parser.parse_args()

    app = Application()
    app_runner = runner.DaemonRunner(app)
    app_runner.do_action()
```

The problem with this design is: what happens if, after `Queue.get` returns, the network dies and the message isn't delivered? I'd like to be able to recover the message in that case. So I imagine doing something like:

```
def get(self):
    value = self._queue.popleft()
    try:
        self.return(value)
    except NetworkError:
        self._queue.appendleft(value)
```

Does that make sense? How do you cope with this in your own APIs?

**Comment by bombela** [comment]
You would have to implement some acknowledgment system. Where you get a msg
in two steps. First getting the message then committing it. Of course you
now have to decide what happens if a msg was first retrieved but never
committed. You could decide that retrieved but not committed msgs are to
but put back on the pool of msgs after some time. Of course you still have
to think about possible double work. Welcome in the hard world of
distributed computing. :)

**Comment by grantjenks** [comment]
Does zerorpc not know when a return value is successfully delivered? I had hoped to see a kind of "@zerorpc.rollback(...)" decorator which would supply a function to be called with the original arguments and return value in the case that the message was not successfully delivered back to the client.

What about with streaming responses? Do you send the second value in an iterator only after the first has been acknowledged as received?

**Comment by bombela** [comment]
zerorpc doesn't know if the return value was successfully delivered. But
remember that in a distributed system, even if the return value is
delivered properly, nothing tells you if the receiver of the value did work
properly on it (crash, bugs... etc). So in my humble opinion the logic of
retrying and ensuring consistency is higher up the stack.

Streaming responses: zerorpc doesn't really know if the response was
properly delivered. In the details, it will send all the values in order,
and when the receiving buffer is full, the sender (ie: the server) will
wait for the receiving end (ie: the client) to notify of available space in
the receiving buffer. Added to that, you have the heartbeat mechanism which
ensures that both sides are still connected at the zerorpc layer.

In the end, you probably want to handle the notion of successful completion
of work higher up your in your logic. Using a consistent database for
example could help (like etcd and the like). Another solution could be to
record errors and progress in your monitoring system, and retry tasks
without progress after some predetermined timeout, etc. A way that I usual
find useful to think about theses problems is to map it to the real world,
with human as process, and mail as data moving around...

On a side note, lets say that you get an ACK msg to confirm that the msg
was received. How do you confirm that the ACK msg itself was received? And
so on? I am sure you can find plenty of doc online about the complexity of
distributed system ;)

best,
fx
