### ISSUE TITLE
Possible to call function on client

### ISSUE THREAD

**Issue by eoinmurray** [0rpc/zerorpc-python#117]
Say you have zerorpc connected between a raspberry pi and a server. The raspberry pi is connected to the internet but is in some unknown location so you don't have the option of binding an IP address or port to it.

Is it possible to do a remote call to the raspberry pi using zero rpc; something like the following:

    # server.py
    import zerorpc

    s = zerorpc.Server()
    s.bind("tcp://0.0.0.0:4242")
    s.run()
    s.HelloRPC()

and the client:

    # client.py
    import zerorpc

    class HelloRPC(object):
        def hello(self):
            return "Hello from client"

    c = zerorpc.Client(HelloRPC())
    c.connect("tcp://127.0.0.1:4242")

**Comment by bombela** [comment]
You can bind or connect either way from client or server, in your example, simply swap Server/Client between your two files:

```
# client_waiting_for_rasberry_to_connect.py
import zerorpc

s = zerorpc.Client()
s.bind("tcp://0.0.0.0:4242")
s.run()
s.HelloRPC()
and the client:

# server_on_rasperry_pi.py
import zerorpc

class HelloRPC(object):
    def hello(self):
        return "Hello from client"

c = zerorpc.Server(HelloRPC())
c.connect("tcp://127.0.0.1:4242")
```

**Comment by eoinmurray** [comment]
This doesn't seem to work for me, I get the error:

    zerorpc.exceptions.TimeoutExpired: timeout after 30s, when calling remote method run

Does this mean that the client in `client_waiting_for_rasberry_to_connect.py` thinks that `run` is a remote command, instead of a command to wait until connection from the raspberry pi?

In this case `server_on_rasperry_pi.py` just exits without waiting for a connection.

**Comment by eoinmurray** [comment]
I have the solution, you need to put the `run()` command after the server on the raspberry pi as follows:

    # server_on_rasperry_pi.py
    import zerorpc

    class HelloRPC(object):
        def hello(self):
            print "request"
            return "Hello from client"

    c = zerorpc.Server(HelloRPC())
    c.connect("tcp://127.0.0.1:4242")
    c.run()

    # client_waiting_for_rasberry_to_connect.py
    import zerorpc

    s = zerorpc.Client()
    s.bind("tcp://0.0.0.0:4242")
    print s.hello()

**Comment by eoinmurray** [comment]
Yes the above code does work with a remote raspberry pi.
