### ISSUE TITLE
add benchmark

### ISSUE THREAD

**Issue by nautilus28** [0rpc/zerorpc-python#119]
Hi,

is there any benchmark script to evaluate the performance of zerorpc-python?

Thanks,
Canh

**Comment by bombela** [comment]
Not that I recall. I remember bench-marking few years ago, but I can't remember what I did with my scripts. Anyway, don't expect C++-like performances, we are talking Python here. 

By experience, it's fast enough for db constrained services. Python and gevent are pretty slow CPU-wide, so zerorpc won't be the limiting factor in most cases. Of course, don't expect something as fast as Redis or ZMQ in C/C++ either ;)

zerorpc is basically a nice (gevent style async) API atop zmq for convenient RPCs. You can definitively merge zerorpc and zmq.

What are you trying to achieve? I might be able to give you some insight.

**Comment by nautilus28** [comment]
Thanks for your response.

I'm looking for a Celery alternative to build an internal web-data processing system. I believe the zerorpc's transaction speed should be (nearly) fast as zmq. Since my internal service requires a lot of different work queues (channels), I'm curious about the Event Layer, maybe I will write a script to benchmark that feature.

Thanks,
Canh

**Comment by bombela** [comment]
zerorpc definitively adds some overhead atop ZMQ. You want to benchmark zerorpc.Client and zerorpc.Server directly to see how fast it is fore you. But for a celery like type of work, zerorpc will definitively be fast enough.

The event layer is simply a minimal abstraction above ZMQ sockets. The goal was to permit non-zmq event channels, proxify zerorpc for example, and make unit testing a bit easier. Don't bother bench-marking this part.

**Comment by nautilus28** [comment]
thanks @bombela
