### ISSUE TITLE
Flush timed-out messages

### ISSUE THREAD

**Issue by kmcheung12** [0rpc/zerorpc-python#121]
Hi,

I am following https://github.com/0rpc/zerorpc-node/issues/19

I'm encountering same situation. 

How to cancel client requests, which are sent during server downtime, when my server is brought back to live? Right now we are relying on timestamp. But I think simply dropping the message would be a more elegant way of handling.

You mentioned it can be done with "hooks". Can you elaborate more on this?

Thanks

**Comment by bombela** [comment]
zerorpc uses zmq which keeps a queue of outgoing messages until they are delivered. Its possible to configure the zmq sockets to a limit of a single queued message but then performances might suffer (python being so slow compared to zmq, I am not 100% sure).
