### ISSUE TITLE
Use ZRPC-specific logger for logging

### ISSUE THREAD

**Issue by pixelbombs** [0rpc/zerorpc-python#122]
Hey guys,

First and foremost, thanks for this library, it is super sweet and has saved us a ton of time in building client/server models.
My issue here is that because ZeroRPC is not implemented with a ZeroRPC-specific logger, the debug messages can't be squelched:
```
DEBUG - 2015-07-30 17:18:51,044 [148]: --> new channel 104d9442-6bd3-41c4-9703-a9f29182232e
DEBUG - 2015-07-30 17:18:51,049 [140]: -x- closed channel 104d941a-6bd3-41c4-9703-a9f29182232e
fio-2.1.10
DEBUG - 2015-07-30 17:18:51,049 [148]: --> new channel 104d9443-6bd3-41c4-9703-a9f29182232e
DEBUG - 2015-07-30 17:18:51,051 [140]: -x- closed channel 104d941b-6bd3-41c4-9703-a9f29182232e
fio-2.1.10
```
And there's a ton of it. Everywhere. So much noise. Obviously I could modify the ZeroRPC code locally, but that's unideal since we'd have to then redistribute our own version of it.

I think the fix here is to use a ZeroRPC logger instead of the root logger. Is anyone else interested in this feature? It's probably easy enough that I could fork the repo and merge back based on popular demand.

Thanks again guys,
--Eddie

**Comment by bombela** [comment]
Sounds like a good idea. Make sure that zerorpc cli and the tests are still
able to output logs for easy debugging. Pull request welcome :)

**Comment by pixelbombs** [comment]
@bombela Awesome, I'll do that :D

**Comment by rtobar** [comment]
Hi,

I ran into this same issue with a newer version of zerorpc and I still see some debug calls being done on the root logger. Was this issue actually addressed at some point? If not I'd like to fix it on the latest version and request a pull. Please let me know
