### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by marcellobarile** [0rpc/zerorpc-python#124]
Hi,
I'm trying to use zerorpc in a Node.js project; the Node.js application should talk with a Python script but, as soon as I call the "invoke" method from Node.js, I get "Segmentation fault (core dumped)" back from the Python script. I'm trying to figure out what's causing it but I've no idea at the moment. Any help or hint will be appreciated :-)
Edit: I've a Python 2.7.9 version installed and a Ubuntu 15.04
Edit 2:
I've run the program with gdb and that's what I've got:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdd993700 (LWP 24781)]
[New Thread 0x7fffde194700 (LWP 24780)]
[New Thread 0x7fffdee8f700 (LWP 24779)]

Program received signal SIGSEGV, Segmentation fault.
0x00000000004a9d20 in ?? ()

**Comment by bombela** [comment]
zerorpc-python doesn't contain non-python code itself, thus any pagination fault is likely a problem outside of it. Feel free to provide some code examples.
