### ISSUE TITLE
msgpack Error

### ISSUE THREAD

**Issue by liuyangc3** [0rpc/zerorpc-python#125]
Hi,
I followed the doc from http://www.zerorpc.io/

after pip install zererpc,I wrote the 'Hello World' Server and Client  example  on two different Linux Server.

and I got this from Server
```
# python s.py 
ERROR:zerorpc.channel:zerorpc.ChannelMultiplexer ignoring error on recv
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/zerorpc/channel.py", line 79, in _channel_dispatcher
    event = self._events.recv()
  File "/usr/lib/python2.6/site-packages/zerorpc/events.py", line 332, in recv
    event = Event.unpack(blob)
  File "/usr/lib/python2.6/site-packages/zerorpc/events.py", line 188, in unpack
    unpacker.feed(blob)
  File "msgpack/_unpacker.pyx", line 318, in msgpack._unpacker.Unpacker.feed (msgpack/_unpacker.cpp:318)
TypeError: 'Frame' does not have the buffer interface
ERROR:zerorpc.channel:zerorpc.ChannelMultiplexer ignoring error on recv
```

here is the code:
```
#Server
import zerorpc

class HelloRPC(object):
    def hello(self, name):
        return "Hello, %s" % name

s = zerorpc.Server(HelloRPC())
s.bind("tcp://0.0.0.0:1234")
s.run()
```

```
#Client
import zerorpc

client = zerorpc.Client()
client.connect("tcp://172.16.200.84:1234")
print(client.hello("World"))
```

I'am a new user,What did I miss?

**Comment by bombela** [comment]
Hello,

I can't reproduce the error. What are your version of python + zerorpc and dependencies?

Maybe run:
```
python --version
pip show zerorpc gevent pyzmq msgpack-python
```

Best,
fx

**Comment by liuyangc3** [comment]
Python 2.6.6 defualt version on CentOS 6

all packages installed through `pip install zerorpc`

Name: zerorpc
Version: 0.5.1
Name: gevent
Version: 1.0.2
Name: pyzmq
Version: 14.7.0
Name: msgpack-python
Version: 0.4.6

**Comment by liuyangc3** [comment]
here is my little digging
https://github.com/zeromq/pyzmq/issues/719
 
I think it is the buffer interface problem but  dont konw wether ti is right.

**Comment by liuyangc3** [comment]
hi fx,
I installed zerorpc on my PC windows10

```
Python 2.7.8
----
Name: zerorpc
Version: 0.5.1
----
Name: gevent
Version: 1.0.1
----
Name: msgpack-python
Version: 0.4.4
```
the dome still got problem on server side
```
ERROR:zerorpc.channel:zerorpc.ChannelMultiplexer ignoring error on recv
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\zerorpc\channel.py", line 79, in _channel_dispatcher
    event = self._events.recv()
  File "C:\Python27\lib\site-packages\zerorpc\events.py", line 339, in recv
    event = Event.unpack(blob)
  File "C:\Python27\lib\site-packages\zerorpc\events.py", line 196, in unpack
    unpacked_msg = unpacker.unpack()
  File "C:\Python27\lib\site-packages\msgpack\fallback.py", line 491, in unpack
    ret = self._fb_unpack(EX_CONSTRUCT, write_bytes)
  File "C:\Python27\lib\site-packages\msgpack\fallback.py", line 419, in _fb_unpack
    typ, n, obj = self._read_header(execute, write_bytes)
  File "C:\Python27\lib\site-packages\msgpack\fallback.py", line 309, in _read_header
    c = self._fb_read(1, write_bytes)
  File "C:\Python27\lib\site-packages\msgpack\fallback.py", line 275, in _fb_read
    return buffs[self._fb_buf_i][self._fb_buf_o - n:self._fb_buf_o]
  File "C:\Python27\lib\site-packages\zmq\sugar\frame.py", line 15, in __getitem__
    return self.get(key)
  File "zmq/backend/cython/message.pyx", line 369, in zmq.backend.cython.message.Frame.get (zmq\backend\cython\message.c:3381)
TypeError: expected str, got: slice(0, 1, None)
```

then I update msgpack to 0.4.6,it works,  maybe there is bug in msgpack 0.4.4
maybe  the doc need a update to mention that the version of dependent package, I think
 
and on the CentOS it still not work
I think maybe it's Python version issue,I i wll update the Linux Python to 2.7 soon,and have a try

**Comment by liuyangc3** [comment]
hi fx,
it is the python version

```
[root@bj-zb-test-jenkins201 ~]# /usr/bin/python2.6 c.py 
ERROR:zerorpc.channel:zerorpc.ChannelMultiplexer ignoring error on recv
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/zerorpc/channel.py", line 79, in _channel_dispatcher
    event = self._events.recv()
  File "/usr/lib/python2.6/site-packages/zerorpc/events.py", line 332, in recv
    event = Event.unpack(blob)
  File "/usr/lib/python2.6/site-packages/zerorpc/events.py", line 188, in unpack
    unpacker.feed(blob)
  File "msgpack/_unpacker.pyx", line 318, in msgpack._unpacker.Unpacker.feed (msgpack/_unpacker.cpp:318)
TypeError: 'Frame' does not have the buffer interface

....
  
[root@bj-zb-test-jenkins201 ~]# /usr/local/bin/python -V
Python 2.7.6
[root@bj-zb-test-jenkins201 ~]# /usr/local/bin/python c.py 
Hello, RPC
```

**Comment by bombela** [comment]
Thank you for testing in details. I will try reproducing the error using what you have tried and see if this can be fixed or else documented. I am not sure what is Frame. It might be a pyzmq frame actually. So the problem could be in fact in pyzqm.

**Comment by liuyangc3** [comment]
'Frame' is zmq frame

> /usr/lib/python2.6/site-packages/zerorpc/events.py(190)unpack()
-> unpacker.feed(blob)
(Pdb) l
185         @staticmethod
186         def unpack(blob):
187             unpacker = msgpack.Unpacker()
188             import pdb
189             pdb.set_trace()
190  ->         unpacker.feed(blob)
191             unpacked_msg = unpacker.unpack()
192  
193             try:
194                 (header, name, args) = unpacked_msg
195             except Exception as e:
(Pdb) b 190
Breakpoint 1 at /usr/lib/python2.6/site-packages/zerorpc/events.py:190
(Pdb) s
TypeError: "'Frame' does not have the buffer interface"
> /usr/lib/python2.6/site-packages/zerorpc/events.py(190)unpack()
-> unpacker.feed(blob)
(Pdb) s
--Return--
> /usr/lib/python2.6/site-packages/zerorpc/events.py(190)unpack()->None
-> unpacker.feed(blob)
(Pdb) p blob
<zmq.sugar.frame.Frame object at 0x7f0bb436db90>

**Comment by liuyangc3** [comment]
probably it is msgpack bug

here is what I do
···
...
(Pdb) blob
<zmq.sugar.frame.Frame object at 0x7fde7a3b9b90>
(Pdb) x = buffer(blob)
(Pdb) x
<read-only buffer for 0x7fde7a3b9b90, size -1, offset 0 at 0x7fde78b90db0>
···
Frame can be  pass into buffer(),but can not run in feed
```
(Pdb) unpacker.feed(blob)
*** TypeError: 'Frame' does not have the buffer interface
(Pdb) import zmq
(Pdb) y = zmq.sugar.frame.Frame()
(Pdb) unpacker.feed(y)           
*** TypeError: 'Frame' does not have the buffer interface
```
so I make anthoer unpacker
```
(Pdb) myunpacker = msgpack.Unpacker()
(Pdb) myunpacker.feed(blob)
*** TypeError: 'Frame' does not have the buffer interface
```
srting is ok ...
```
(Pdb) myunpacker.feed('string')
(Pdb) 
```

**Comment by methane** [comment]
@liuyangc3 pyzmq has two Frame backend, cffi and cython.
Cython backend supports buffer protocol.  But cffi backend doesn't.
Does your Python 2.6 use cython backend?

**Comment by liuyangc3** [comment]
Hi,@methane
I am not sure yet,How can I  check the backend type? 
the PyZMQ document said that cffi is used for PyPy.

**Comment by methane** [comment]
```
In [6]: repr(zmq.backend.Frame)
Out[6]: "<class 'zmq.backend.cython.message.Frame'>"
```

**Comment by bombela** [comment]
I guess zerorpc could use Frame.buffer, as documented here: https://zeromq.github.io/pyzmq/api/zmq.html#frame

Instead of assuming Frame will implement the buffer interface.

**Comment by liuyangc3** [comment]
@methane 
```
>>> repr(zmq.backend.Frame)
"<type 'zmq.backend.cython.message.Frame'>"
```

**Comment by methane** [comment]
OK. It may be Python 2.6's problem.

The biggest point is... I don't want to pay any effort for supporting Python 2.6.
I believe new program should written for at least Python 2.7.
Python 2.6 shipped via yum is only for applications shipped via yum.

**Comment by liuyangc3** [comment]
@methane @bombela ,thanks for your help though.
I guess it may be different api that How Cpython implement the buffer interface in Python 2.6 than 2.7.

2.7 use new structure for memview interface

**Comment by Olmer1st** [comment]
I have same issue: https://github.com/0rpc/zerorpc-python/issues/133
