### ISSUE TITLE
zerorpc not working on CentOs7

### ISSUE THREAD

**Issue by Olmer1st** [0rpc/zerorpc-python#133]
Hi,
I'm new user and try to use zerorpc on CentOS7.
On Ubuntu same code work great.

python2.7 -V: Python 2.7.9
Metadata-Version: 2.0
Name: zerorpc
Version: 0.5.2
Summary: zerorpc is a flexible RPC based on zeromq.
Home-page: https://github.com/0rpc/zerorpc-python
Author: François-Xavier Bourlet <bombela+zerorpc@gmail.com>.
Author-email: UNKNOWN
License: MIT
Location: /usr/local/lib/python2.7/site-packages

Metadata-Version: 2.0
Name: gevent
Version: 1.0.2
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Denis Bilenko
Author-email: denis.bilenko@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages

Metadata-Version: 2.0
Name: pyzmq
Version: 15.1.0
Summary: Python bindings for 0MQ
Home-page: https://pyzmq.readthedocs.org
Author: Brian E. Granger, Min Ragan-Kelley
Author-email: zeromq-dev@lists.zeromq.org
License: LGPL+BSD
Location: /usr/local/lib/python2.7/site-packages

Metadata-Version: 2.0
Name: msgpack-python
Version: 0.4.6
Summary: MessagePack (de)serializer.
Home-page: http://msgpack.org/
Author: INADA Naoki
Author-email: songofacandy@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages

Code Server: 
class channelRPCServer(object):
     def test(self, name):
         return "Test done. Received text, %s" % name
        
            
server = zerorpc.Server(channelRPCServer())
server.bind("tcp://0.0.0.0:4242")
print "RPC Server binded" 
server.run()

Client cli: zerorpc tcp://127.0.0.1:4242 test RPC

Please help.
Thanks

**Comment by Olmer1st** [comment]
and how to solve it? I found this error too, but still don't have solution?!

**Comment by bombela** [comment]
Do you get the same error as #125: "TypeError: 'Frame' does not have the buffer interface" ?

**Comment by Olmer1st** [comment]
Not the same, but like :
ERROR:zerorpc.channel:zerorpc.ChannelMultiplexer ignoring error on recv
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zerorpc/channel.py", line 79, in _channel_dispatcher
    event = self._events.recv()
  File "/usr/lib/python2.7/site-packages/zerorpc/events.py", line 341, in recv
    event = Event.unpack(get_pyzmq_frame_buffer(blob))
  File "/usr/lib/python2.7/site-packages/zerorpc/events.py", line 198, in unpack
    unpacked_msg = unpacker.unpack()
  File "/usr/lib64/python2.7/site-packages/msgpack/fallback.py", line 570, in unpack
    ret = self._fb_unpack(EX_CONSTRUCT, write_bytes)
  File "/usr/lib64/python2.7/site-packages/msgpack/fallback.py", line 498, in _fb_unpack
    typ, n, obj = self._read_header(execute, write_bytes)
  File "/usr/lib64/python2.7/site-packages/msgpack/fallback.py", line 347, in _read_header
    b = ord(c)
TypeError: ord() expected string of length 1, but memoryview found

**Comment by Olmer1st** [comment]
My problem, that our tests on ubuntu succeed. And we started implement zerorpc in our product.
I decided to test it on sandbox machine (CentOS7) and received the error above...

**Comment by Olmer1st** [comment]
Please note same error when using example:
zerorpc --server --bind tcp://*:1234 time

zerorpc --client --connect tcp://127.0.0.1:1234 strftime %Y/%m/%d

**Comment by bombela** [comment]
Definitively something going on between memoryview, buffer, pyzmq and msgpack. I tried working around it but this obviously doesn't work in your case.

My understanding so far is:
 - pyzmq
  - cython code uses buffer on python<2.7 and memoryview on python>=2.7
  - cffi code was buggy for some times but should use the same rules. cffi is mainly for pypy, but I suspect it is used as a fallback when it fails to build using cython.
 - msgpack
  - cython version expects str (of bytes) for python<2.7 but accepts a memoryview on python>=2.7
  - if cython fails to build it uses a pure python fallback. which doesn't handle memory view, only str.
 - zerorpc
  - if python <2.7, converts pyzmq buffer to str[], for python>=2.7 expect pyzmq frame to yield a memoryview.

zerorpc doesn't handle the cases when pyzqm and msgpack are built without using cypython, which seems to be your case.

The workaround rules are complex, and sometimes even buggy on previous version of pyzmq/msgpack/zerorpc.

I will review them again, and try to come up with something smarter this time.

**Comment by Olmer1st** [comment]
Thanks for respond. 
Why it's work on Ubuntu machine? same config, just not a CentOS?
I believe withou cypython too...

**Comment by bombela** [comment]
I think it uses cython on ubuntu? On my ubuntu laptop it does build with cython (same on travis btw). I have no idea why it behaves differently on centos.

**Comment by methane** [comment]
How did you installed msgpack?

**Comment by Olmer1st** [comment]
Nothing special,  as i remember 'pip install zerorpc' installed msgpack too

**Comment by methane** [comment]
`pip install msgpack-python` shouldn't require cython to build extension module.
Cythonized c files are bundled into tar.gz package.

Do you installed c++ compiler?  If not, install g++ and reinstall msgpack-python.

**Comment by Olmer1st** [comment]
Yes. c++ installed before, i compiled nodejs version.
Should I compile msgpack too?

**Comment by methane** [comment]
Yes. fallback module is very slow on CPython.

**Comment by Olmer1st** [comment]
Well done! It's OK!
Thanks!

**Comment by bombela** [comment]
Interesting, thank you for the troubleshooting guys. I guess we shouldn't use the fallback for any decent performances, but we need a better way to understand what is happening. I am opening a new issue to track that.

**Comment by Olmer1st** [comment]
Hi again,
Forgotten to add, that Cython not installed on CentOS7 by default.
To make everything work (uninstall msgpack with pip): 
1. installed latest cython library with yum
2. installed latest cython library with pip
3. compile msgpack and install

**Comment by methane** [comment]
Cython is not required to install msgpack.
C++ compiler is required instead.

**Comment by Olmer1st** [comment]
In my case, i tried execute 'python setup.py build'  without installing Cython and I received an error : "... can't locate cython library..." or something like this.... than I installed Cython just for python. still received same error. than installed  rpm of cython and compiled again. Now succeed. Checked zerorpc cli and everything worked .

**Comment by methane** [comment]
Cythonized c++ source isn't in git repository, but in source distribution (.tar.gz) on PyPI.
So you can `pip install msgpack-python` without cython, but you should have cython when
install from git repository.

**Comment by Olmer1st** [comment]
I understand. But my problem was when I used pip install msgpack-python zerorpc had exception.
Just when i compiled msgpack the problem resolved.
