### ISSUE TITLE
Work with msgpack fallback.

### ISSUE THREAD

**Issue by bombela** [0rpc/zerorpc-python#134]
Its better to work with the msgpack pure python fallback than not at all. Example of why it sucks when it doesn't work: #133.

**Comment by methane** [comment]
msgpack fallback module is provided for these cases:

* Can't use or build extension module (e.g. GAE/Python)
* PyPy

Does zerorpc-python support such environment?

**Comment by bombela** [comment]
Well GAE might be worthwhile to support, but I have no time to test this.
