### ISSUE TITLE
Allow handing events without blocking

### ISSUE THREAD

**Issue by hmeine** [0rpc/zerorpc-python#145]
I would like to use zerorpc instead of my own, hand-made (and inferior) 0MQ-based RPC system.

However, I need a (non-blocking) `handle_events()`-like API instead of just the `run()` method, which I can use in a polling-like fashion within a different main loop.

I had a look at how `run()` is implemented, but I know nothing about gevents yet, so it is not easy to achieve my goal myself.

**Comment by bombela** [comment]
gevent.spawn(my_zerorpc_server.run)

And it's running in its own coroutine.

**Comment by hmeine** [comment]
Thanks. My main program does not use gevents, though. (Imagine a mainloop that allows me to repeatedly call a function.)  Is there a simple way of polling either zerorpc directly, or with gevents (which I don't know anything about yet – except the concepts of coroutines, and the API being apparently threads-like)?

**Comment by bombela** [comment]
Sadly, zerorpc depends on gevent, and when you use zerorpc, your program becomes a gevent program :/ I am thinking solving this problem in the long term by supporting different IO models. But for now, you need to be gevent away one way or another.
