### ISSUE TITLE
Add multiple classes to same server

### ISSUE THREAD

**Issue by mrlarssen** [0rpc/zerorpc-python#147]
Is it possible to add multiple classes to the same server? Or how is communication with python server done when a project contains multiple classes?

Is this a possible solution?

s1 = zerorpc.Server(Class1())
s1.bind("tcp://0.0.0.0:4242")
s1.run()

s2 = zerorpc.Server(Class2())
s2.bind("tcp://0.0.0.0:4242")
s2.run()

**Comment by bombela** [comment]
Sadly this is not possible. Of course you can mix classes yourself,
namespace by hand your methods etc. At this time zerorpc doesn't support
multiple "services" on a single endpoint.

**Comment by mrlarssen** [comment]
Ok, thank you for a quick reply. Using zerorpc-node and zerorpc-python with docker, and it is working like a charm so far.
