### ISSUE TITLE
Passing an instantiated object or initializing a class variable through a class method causes error in running server ZeroRPC

### ISSUE THREAD

**Issue by angelosembrano** [0rpc/zerorpc-python#155]
So I have this setup for my back-end, Python handling data-mining and communicates with the database (MongoDB through PyMongo), and Node.js/Restify invoking the Python methods through ZeroRPC.

I have the following classes with functions as follows:

- `Importer` - imports, transforms, and cleans the data from the csv to json data.
- `Database` - the database object, contains the MongoClient and handles the inserting of the imported data from `Importer`.
- `Analytics` - the object that contains the data mining methods; the one to be passed to the `zerorpc.Server`. Needs to be passed an instance or the `Database` class instead to have access to the database.

So here's how my `app.py` looks like.

    import os
    import zerorpc
    
    from scripts.database import Database
    from scripts.importer import Importer
    from scripts.analytics import Analytics
    
    from utils.timer import time_function
    
    ROOT = os.path.dirname(__file__)
    
    
    if __name__ == "__main__":
        importer = Importer()
    
        db = Database(data=importer.data)
    
        services = Analytics(db)
    
        server = zerorpc.Server(services)
        server.bind("tcp://0.0.0.0:1234")
        server.run()

Yet it shows this error:

    Traceback (most recent call last):
      File "D:/Projects/Dashboards/app/app.py", line 28, in <module>
        server = zerorpc.Server(Analytics())
      File "D:\Projects\Dashboards\env\lib\site-packages\zerorpc\core.py", line 292, in __init__
        pool_size, heartbeat)
      File "D:\Projects\Dashboards\env\lib\site-packages\zerorpc\core.py", line 72, in __init__
        self._methods[k] = rep(functor)
      File "D:\Projects\Dashboards\env\lib\site-packages\zerorpc\decorators.py", line 36, in __init__
        self.__name__ = functor.__name__
      File "D:\Projects\Dashboards\env\lib\site-packages\pymongo\collection.py", line 262, in __getattr__
        name, full_name, full_name))
    AttributeError: Collection has no attribute '__name__'. To access the sales.__name__ collection, use database['sales.__name__'].
    
    Process finished with exit code 1

**So at this point I realized, "maybe because I passed an instance of the object and not the object itself."**

So I transformed my `Analytics` into this:

    from bson.son import SON
    import datetime
    
    class Analytics(object):
        # def __init__(self, database):
        #     self.db = database.db
        #     self.sales = database.tb_sales
    
        @classmethod
        def connect_db(cls, database):
            cls.db = database.db
            cls.sales = database.tb_sales

        ...other methods here...

Where the class method `connect_db` was once the `__init__` of `Analytics`. And thus my `app.py` is changed to:

    import os
    import zerorpc
    
    from scripts.database import Database
    from scripts.importer import Importer
    from scripts.analytics import Analytics
    
    from utils.timer import time_function
    
    ROOT = os.path.dirname(__file__)
    
    if __name__ == "__main__":
        importer = Importer()
    
        db = Database(data=importer.data)
 
        Analytics.connect_db(database=db)
    
        server = zerorpc.Server(Analytics())
        server.bind("tcp://0.0.0.0:1234")
        server.run()

**But still it shows THE SAME ERROR.**

Why is that? Any ideas?
Somehow I think it has something to do of `zerorpc`'s nature of getting the `__name__` of functions so that it can be invoked by the client? Just my two cents.

**Comment by bombela** [comment]
For the sake of completion, here is my answer for the same question on [stackoverflow](http://stackoverflow.com/questions/41137602/passing-an-instantiated-object-or-initializing-a-class-variable-through-a-class/41292606#41292606):

zerorpc.Server does expect a class instance. By default it tries to guess the service name via the `instance.__name__` attribute which is not available in your case.

You can set the name yourself like so:

    server = zerorpc.Server(services, name="mysuperservice")
