### ISSUE TITLE
Support keyword arguments

### ISSUE THREAD

**Issue by petr-motejlek** [0rpc/zerorpc-python#157]
Seems like passing keyword arguments using zerorpc is not supported. This should either be fixed or at least documented. On either side it's very strange that such a foundation feature of Python has been neglected.

This fails on Python 3.5

# client
    import zerorpc

    c = zerorpc.Client()
    c.connect("tcp://127.0.0.1:4242")

    c.test(i=10)

# server
    import zerorpc

    class MyRPC:
        def test(self, i):
            return i

    s = zerorpc.Server(MyRPC())
    s.bind("tcp://0.0.0.0:4242")
    s.run()

**Comment by bombela** [comment]
Hello, that is correct. Keywords arguments are not supported and it is a conscious decision. zerorpc is eventually cross-language. Most languages do not support keyword arguments.
