### ISSUE TITLE
zerorpc.ChannelMultiplexer, unable to route event

### ISSUE THREAD

**Issue by romanesko** [0rpc/zerorpc-python#179]
```
zerorpc.ChannelMultiplexer, unable to route event: <b'\x00\x92r\xc4\xe2'> _zpc_hb {'response_to': b'd79c7130db9447a4aad01c4f1ecef0ff', 'v': 3, 'message_id': b'd79c7131db9447a4aad01c4f1ecef0ff'} [...]
```
on the server after the same client disconnects and connects again

**Comment by bombela** [comment]
Its an heartbeat event response. Since the client disconnected, the server couldn't send the heartbeat message back. This is logged because it can help diagnose other network problems. In your case, this is totally harmless.
