### ISSUE TITLE
Meet Problem with Pyinstaller

### ISSUE THREAD

**Issue by friddle** [0rpc/zerorpc-python#180]
I pack python file include zerorpc,but meet the problem like that 

![image](https://user-images.githubusercontent.com/2897690/32359922-5476e39c-c01f-11e7-99d5-2bbefcbfaf9f.png)

I found this issues:https://github.com/zeromq/pyzmq/issues/999
copy all python file to zmq\backend\cython\
but throw other exception:

cython not found.

pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
pyinstaller 3.3
Darwin sckMacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

Please Helo to fix this problem

**Comment by glucee** [comment]
how did you fix this ?
