### ISSUE TITLE
zerorpc used in django with gunicorn gevent worker block client request

### ISSUE THREAD

**Issue by zyi1992** [0rpc/zerorpc-python#182]
I have seen the issues [issues:123](https://github.com/0rpc/zerorpc-python/issues/123) before and I upgrade the pyzmq to 15.3.0 but it seems nothing changed, but it only work when i change pyzmq version to 13.1.0 , Is there still a bug in gunicorn gevent with pyzmq or  i missed some procedure to solve it.

**Comment by bombela** [comment]
I am not aware of any specific bug, and I don't have the time to experiment. Make sure to aware of the consequences of using monkey patching.
