### ISSUE TITLE
Compatibility with other RPC libs

### ISSUE THREAD

**Issue by sasmaster** [0rpc/zerorpc-python#183]
Hi. Is this lib supposed to work with https://github.com/rpclib/rpclib  ?

Both implement the same rpc standard.But it doesn't work.

**Comment by sasmaster** [comment]
This one https://github.com/msgpack-rpc/msgpack-rpc-python
does work with c++ rpclib.

**Comment by bombela** [comment]
zerorpc has its own RPC protocol atop of zeromq, using message-pack for serialization. It is not an implementation of messagepack-rpc.
