### ISSUE TITLE
To disconnect() or close()

### ISSUE THREAD

**Issue by hgezim** [0rpc/zerorpc-python#192]
First, thank you for this awesome library!

I've got a method that calls an rpc method like so:

```python

def generate_label(params):
    c = zerorpc.Client()
    c.connect("tcp://127.0.0.1:4242")
```

I started getting a `error: [Errno 24] Too many open files` open error. It occurred to me that I'm not closing this connection at all. I couldn't find in the docs what the difference between `disconnect()` and `close()` is. Which one should I use?

**Comment by bombela** [comment]
instead of creating a new client every time, simply connect one at the
beginning of your program. zerorpc.Client is designed to be used this way.
