### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by adrianschneider94** [0rpc/zerorpc-python#203]
Hi,

I would like to use namespaces for my ZeroRPC Server. So that I can structure the functions. https://github.com/kmanley/zerorpc/ implements this. Is this possible with zerorpc-python?

Best wishes,
Adrian Schneider

**Comment by bombela** [comment]
note: kmanley/zerorpc is unrelated to 0rpc/*.

zerorpc-python doesn't handle namespacing for you.

With that said, `zerorpc.Server` accepts the set of methods to expose as a dict of `(fname: str -> F: DecoratorBase)` . `zerorpc.Server` automatically wraps any `F` not of type `DecoratorBase`  into a `decorators.rep`. And finally, any non-dict set of methods is converted to a dict (https://github.com/0rpc/zerorpc-python/blob/master/zerorpc/core.py#L75).

All of that to say that you are free to build your own mapping of `fname: -> F: DecoratorBase`, where you can prefix fname the way you want. Example `{ 'time_get': ..., 'time_set': ..., 'file_read': ..., 'file_write': ...,}`.

On the client side it would look like so: `client.time_get(...)`.

Of course, you can inherit from `zerorpc.Client` and add override `__call__` (https://github.com/0rpc/zerorpc-python/blob/master/zerorpc/core.py#L240) adding some default prefix before a call for example.

**Comment by adrianschneider94** [comment]
Great, thanks!

**Comment by adrianschneider94** [comment]
Great, thanks!
