### ISSUE TITLE
Are there API docs?

### ISSUE THREAD

**Issue by KeithTt** [0rpc/zerorpc-python#207]
Is there API docs besides the examples on the official website?

**Comment by gabrielgrant** [comment]
AFAIK the README and http://www.zerorpc.io/ just about cover it. Are there specific questions you have that aren't covered?

**Comment by KeithTt** [comment]
It is enough for common usage. Thanx,

**Comment by KeithTt** [comment]
@gabrielgrant It seems incompatible with python 3.7.

**Comment by DavidAntliff** [comment]
@KeithTt in what way? I'm using it with 3.7.1 and haven't seen any problems.

**Comment by DavidAntliff** [comment]
@KeithTt that reminds me, I had to pin gevent to a slightly earlier version. I forget the details, but I can check on Monday...

**Comment by DavidAntliff** [comment]
I checked my dependencies (I'm using Yocto rather than pip to install packages with native extensions) and it seems that I pinned `python3-greenlet` to 0.4.13-r0, as the latest version (at the time I set everything up, which was 6+ months ago) did not work, perhaps in a similar way to your error.
