### ISSUE TITLE
Memory leak when using async calls

### ISSUE THREAD

**Issue by aleksa2808** [0rpc/zerorpc-python#215]
Hey, I've been using this library for a bit and I came upon an issue where, if I call the remote methods with the 'async' argument enabled, the client script starts consuming about 200MB per second, releasing them only when I interrupt it.

When I call methods without the async argument, the memory that the script consumes is constant.

I'm using Python 3.6.7 with `pip freeze` giving:  

```
future==0.17.1
gevent==1.5a1
greenlet==0.4.15
msgpack-python==0.5.6
pyzmq==18.0.1
zerorpc==0.6.1
```

The client and server scripts that are causing the issue on my machine are:

```python
# client.py
import zerorpc

client = zerorpc.Client()
client.connect("tcp://127.0.0.1:1234")

while True:
    client.async_method(async=True)

# server.py
import zerorpc

class API():
    def async_method(self):
        pass

s = zerorpc.Server(API())
s.bind("tcp://0.0.0.0:1234")
s.run()
```

**Comment by bombela** [comment]
If you never resolve the future, you will never release resources.

**Comment by aleksa2808** [comment]
Ah, I see. Thought that if nothing was referencing the result the GC would clean it up.
