### ISSUE TITLE
Server shutdown timeout

### ISSUE THREAD

**Issue by Evidlo** [0rpc/zerorpc-python#216]
I'd like my server to shut down after N seconds of no client activity. Is there a way to do this?

My application is a CLI program for accessing an encrypted database. Database decryption is slow, so I fork a server process to keep the database open and communicate with it through a unix socket. The server should shut down 5 minutes after no contact from the client.

**Comment by bombela** [comment]
You can call the `stop()` method on the server whenever you see fit. Keep some sort of timer around, push back the timeout on every request. When timer kicks in, call the `stop()` method.

If you want a fancy integration, implement and load a middleware on the zerorpc context object. Implement hook_server_after_exec and hook_server_inspect_exception.
