### ISSUE TITLE
How to monitor my RPC service based on zeroRPC

### ISSUE THREAD

**Issue by litaotao** [0rpc/zerorpc-python#222]
thanks for building zeroRPC, it's so elegant and simple to use. But in our system, we have many services and each service has different clients which send different calls.

And we want to monitor our rpc services, such as how many calls it has handled, how many calls it is processing, for each call, we want to know it's source, current status and time consumed and other useful indicators.

so to put is simply, how do we can monitor our rpc services based on zeroRPC. 

thanks a lot

**Comment by bombela** [comment]
Hello,

You can register hook functions on the zerorpc context. With that you can
effectively build your monitoring.

Best,
fx

**Comment by litaotao** [comment]
thanks a lot

**Comment by bombela** [comment]
https://github.com/0rpc/zerorpc-python/blob/master/zerorpc/context.py#L117

you pass an object to this function. methods on the object that have
specific names are called at specific places throughout zerorpc.

The list of possible methods is listed below the register function.

**Comment by litaotao** [comment]
thanks for your quickly reply, bellow is what I test the hook functions:


- server

```python
import zerorpc

context = zerorpc.Context()

def info(request_event):
    print('hook_server_before_exec')
    print('### attributes of request_event: ', dir(request_event))
    for key in dir(request_event):
        if '_' not in key:
            print("### {} -> {}".format(key, request_event.__getattribute__(key)))

context._hooks['server_before_exec'] = [info]


s = zerorpc.Server(notifyRPC(), context=context)
s.bind("tcp://0.0.0.0:6001")
s.run()
```

- client

```sh
zerorpc tcp://127.0.0.1:6001 message 'hello world'
```

- result

```sh
taotao@MBP  ~/Desktop/MingShi/MS-MONITOR   master ●  python service.py
hook_server_before_exec
### attributes of request_event:  ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_args', '_header', '_identity', '_name', 'args', 'header', 'identity', 'name', 'pack', 'unpack']
### args -> ['hello world']
### header -> {'message_id': b'4176a4f933684497891b0e2eadb54763', 'v': 3}
### identity -> [<zmq.sugar.frame.Frame object at 0x10fdfef60>]
### name -> message
### pack -> <bound method Event.pack of <zerorpc.events.Event object at 0x10ff55360>>
### unpack -> <function Event.unpack at 0x10fdf4bf8>
hello world
```

```sh
taotao@MBP  ~  zerorpc tcp://127.0.0.1:6001 message 'hello world'
connecting to "tcp://127.0.0.1:6001"
1
```

And my problem is that I want to get more details of a request_event, such as its IP address.

**Comment by bombela** [comment]
zmq inherently abstracts connection. zerorpc doesn't know if a request
comes from an existing connection, or new one are it is all hidden away by
zmq.

The identity is the zmq identifier for the request.

zmq offers some way to monitor what is happening, via the monitor socket.
But I am affraid it might be hard to correlate with zmq identity.

note: Do not mutate/access the context privates attribute. Use the public
register_middleware function. Otherwise any internal change will break your
code. You also made your life much harder by trying understand internals
instead of using the obvious API

note2: you can also register hooks on the default context instance if you
wish.

**Comment by litaotao** [comment]
got it, thanks alot
