### ISSUE TITLE
Question: Is there an AsyncIO client?

### ISSUE THREAD

**Issue by imaurer** [0rpc/zerorpc-python#235]
Thanks for this project. Wonderfully done, it has really held up for a long-time and seems very stable. I apologize if I am doing something wrong and that I haven't figured this out on my own from googling/experimenting, but i have some questions:

1. I am attempting to call my ZeroRPC service from an AsyncIO-based application. The AsyncIO call is failing because of what I believe to be an incompatibility between AsyncIO and gevent. Is this assessment correct?

2. I believe the path forward is to create a new AsyncIO client that mimics the existing ZeroRPC client message marshaling behavior (MessagePack, etc.) and handles the socket communication correctly.  Does this seem correct?

3. I guess I am putting a lot of value in the "server side" of this project being the significant value.  Are there any tips/concerns with this approach? Has a project like this been attempted before?

4. Should i be considering different tools? The core python asyncio socket code seems pretty low level. The aiorpc project seems similar, but less battle-tested and I am concerned about the approach especially since my service code is not AsyncIO-based. (I guess this difference in client/server requirements is why I am the only one who has asked for this feature)

Thanks for your time,
Ian

**Comment by bombela** [comment]
On Wed, 26 Aug 2020, 09:27 Ian Maurer, <notifications@github.com> wrote:

> Thanks for this project. Wonderfully done, it has really held up for a
> long-time and seems very stable. I apologize if I am doing something wrong
> or haven't figured this out from googling, but i have some questions:
>
>    1.
>
>    I am attempting to call my ZeroRPC service from an AsyncIO-based
>    application. The AsyncIO call is failing because of what I believe to be an
>    incompatibility between AsyncIO and gevent. Is this assessment correct?
>
> yes you are correct.

>
>    1.
>    2.
>
>    I believe the path forward is to create a new AsyncIO client that does
>    the marshaling of the client call that mimics the message format of the
>    ZeroRPC. Does this seem correct?
>
> yes. The format is surprisingly simple. and quite readable. it would be
reasonably easy to write an async IO version.

>
>    1.
>    2.
>
>    Are there any tips/concerns with this approach or is anyone aware of
>    existing projects that provide this capability?
>
> You only need to implement the lastest zpc protocol (v3 if I recall) and
simply refuse older version for simplicity. The hardest part might be the
heartbeat system. But you can always start without to get things going. And
you get to use the existing gevent implementation to test against.

**Comment by imaurer** [comment]
Thanks for your insight!
