### ISSUE TITLE
request for an anaconda package

### ISSUE THREAD

**Issue by pushkarnimkar** [0rpc/zerorpc-python#237]
Most of the conda packages for zerorpc are from smaller projects. Such as:

- https://anaconda.org/AmpelProject/zerorpc
- https://anaconda.org/groakat/zerorpc/files

These are not timely updated and painful at times. Do we have an official conda channel? What's the easy way to install through conda?

**Comment by gabrielgrant** [comment]
Conda [supports](https://stackoverflow.com/a/43729857/2604910) installing pip packages within a conda environment. So for the moment you should just be able to do:

```
conda install pip
pip install zerorpc
```

The downside is that this doesn't take advantage of conda to ease the installation of libev (for gevent) and libzmq (for pyzmq), if those are causing problems

**Comment by whophil** [comment]
I'm late to the party here, but I would be happy to create a package for this project on [conda-forge](https://conda-forge.org/).

If there are any maintainers of this project would also be willing to be listed as maintainers on that conda-forge recipe, please let me know.
