### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by cupen** [0rpc/zerorpc-python#241]
I'm looking for a cross-language, lightweight rpc library. This project looks pretty good, but it haven't updated for a long time.

**Comment by bombela** [comment]
What would want to update?

**Comment by cupen** [comment]
> What would you want to update?

Nothing right now. I just afraid it has no maintainer when you are tired to reviewing or developing. 
Anyway, sorry, don't mind that. I'm glad this cool project is still being developed.  :D
