### ISSUE TITLE
Any plan for dropping python2 support? 

### ISSUE THREAD

**Issue by cupen** [0rpc/zerorpc-python#242]
It will lighten the workloads of maintainer.
https://www.python.org/doc/sunset-python-2/

btw: I can make a `pr`, if that's what you like.

**Comment by bombela** [comment]
This project has been stable for years. Keeping support for python2 doesn't cost much at this point.

I suppose that when dependencies bring breaking changes and drop support for python2, it can then be removed.

Does the support for python2 block you in any ways?

**Comment by cupen** [comment]
> I suppose that when dependencies bring breaking changes and drop support for python2, it can then be removed.

I agree totally.

> Does the support for python2 block you in any ways?

Nope. :D
