### ISSUE TITLE
v0.6.3 is incompatible with pyzmq 23.0.0

### ISSUE THREAD

**Issue by chombourger** [0rpc/zerorpc-python#251]
The pyzmq project has recently released 23.0.0

One of the changes highlighted in the release notes is:

> all zmq constants are now available as Python enums (e.g. zmq.SocketType.PULL, zmq.SocketOption.IDENTITY), generated statically from zmq.h instead of at compile-time. This means that checks for the presence of a constant (hasattr(zmq, 'RADIO')) is not a valid check for the presence of a feature. This practice has never been robust, but it may have worked sometimes. Use direct checks via e.g. [zmq.has()](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.has) or [zmq.zmq_version_info()](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.zmq_version_info).

I am getting errors like this one when running against that release
```
AttributeError: module 'zerorpc.gevent_zmq' has no attribute 'PUSH'
```

**Comment by minrk** [comment]
The constants removal from zmq.green was a bug in 23.0, now fixed in 23.1. Feel free to report any compatibility issues upstream!
