### ISSUE TITLE
Issues with long-lasting RPC calls

### ISSUE THREAD

**Issue by makmanalp** [0rpc/zerorpc-python#37]
Test case for Reproduction:

 ```python
import zerorpc

import time
from gevent import monkey; monkey.patch_all()                                                                                                                                                           

class Foo(object):
    
    def wait(self):
        print "Start waitin"
        time.sleep(15)
        print "End waitin"
        return "derp"

s = zerorpc.Server(Foo())
s.bind("tcp://0.0.0.0:3333")
s.run()
```

and the client:

```python
import zerorpc

s = zerorpc.Client("tcp://0.0.0.0:3333", timeout=3000)                                                                                                                                                      
print s.wait()
```

The result for me on the server is:

> /!\ gevent_zeromq BUG /!\ catching after missing event /!\
> zerorpc.ChannelMultiplexer,  unable to route event: _zpc_hb {'response_to': 'e09d15b1-6599-495b-a54d-031e6e7b4039', 'zmqid': ['\x00\xa9\x15J\x94\x8b|O\xf1\xae\x17\xb3M\x82\x8b\xee\x17'], 'message_id': 'e09d15b4-6599-495b-a54d-031e6e7b4039', 'v': 3} [...]

while on the client I get "derp" fine. Without the monkey patch, predictably, the connection is lost due to lack of heartbeat because sleep blocks.

This is a simplification of a larger bug I've been having when dealing with a bunch of workers that all call subprocess to spawn an external executable and do something that takes a while. (With the newest gevent from trunk, there is a subprocess monkey patch).

Any ideas? Zerorpc 0.2.1, gevent 1.0.

**Comment by bombela** [comment]
If it makes you feel better, I took over the maintenance of zerorpc recently. Hopefully I can keep it maintained, and eventually move it forward.
