### ISSUE TITLE
Add pub/sub sample to the documentation page: http://zerorpc.dotcloud.com

### ISSUE THREAD

**Issue by deckarep** [0rpc/zerorpc-python#47]
Hello,

I think this library is amazing and am very impressed with the idea behind zerorpc.  The problem is I'm trying to understand how to properly implement the pub/sub pattern with zerorpc. 

I know there are tests that illustrate this, but I can't figure out how to take the test and separate the logic into a real world example like the examples you have on http://zerorpc.dotcloud.com page.

I would submit a patch of documentation if I understand the way it works myself but so far I can't figure it out.

Also, how can I safely release or close a a zerorpc connection?  If I Ctrl-Z the app while it's running the address doesn't get release and I get Address In Use errors from ZMQ.   At this point, I can't restart the process.  I see how you guys deal with it in the test documents by creating a random ipc channel each time the test is run but how is the deal with, when tcp addresses are dedicated and you need to restart or recover from a crash.

**Comment by bombela** [comment]
I intend to deprecate the PUB/SUB interface at some point. Its better to use zmq directly to do this kind of things.
