### ISSUE TITLE
Use zmq.green instead of gevent_zeromq

### ISSUE THREAD

**Issue by CrackerJackMack** [0rpc/zerorpc-python#50]
as of pyzmq==2.2.0.1  gevent support is included via zmq.green as per zeromq/pyzmq#190 

Since you already required >=2.2.0.1 in setup.py it would make sense to remove the gevent_zeromq.py and use zmq.green directly.

Just an observation

**Comment by bombela** [comment]
A couple years later, it might be useful to benchmark again, and see if zmq.green is now at the same level of speed and maybe the workaround is not necessary anymore.

**Comment by pigmej** [comment]
https://github.com/0rpc/zerorpc-python/issues/137 is related
