### ISSUE TITLE
Auto-configuration with zerorpc helper

### ISSUE THREAD

**Issue by jpetazzo** [0rpc/zerorpc-python#65]
The `zerorpc` helper is very helpful (eh!), and actually, I start 99% of the ZeroRPC servers that I write with `zerorpc --server`, rather than writing a custom script.

However, I also want to do the following:
- enable a specific middleware;
- configure `logging`.

I currently work around the problem by enabling middlewares and setting up logging within the module loaded by `zerorpc --server`; but this leads to code repetition, and is therefore a Bad Thing.

I would love to have (at least) one of the following options:
- the `zerorpc` helper would automatically try to import a module named `zerorpc_settings` (and fail silently if this raises an `ImportError`);
- the `zerorpc` helper would automatically try to import the module indicated by the environment variable `ZERORPC_SETTINGS_MODULE` (if it is set);
- the `zerorpc` helper would allow an optional command-line flag, `--settings`, indicating the name of the module to import;
- if just importing a module feels weak, we could specify a callable instead (and the environment variable would become `ZERORPC_SETTINGS_CALLABLE`).

I'm willing to implement any of those, as long as I know that it has a chance to be merged (provided that the implementation isn't ugly nor kill baby seals).

What do you think, @bombela ?

**Comment by bombela** [comment]
This is probably not going to happen.
