### ISSUE TITLE
Attribute error __name__

### ISSUE THREAD

**Issue by octaviordz** [0rpc/zerorpc-python#66]
Hi
I'm a trying to expose an object. (that I didn't build) but zerorpc fails with an AttributeError complaining about \__name__.

As I have looked at the code I know that the problem is caused because my object's super class has a code like this (simplified):
```python
def get_connection(self):
        if self.con is None:
            self.con = sqlite.connect()
        return self.con

connection = property(get_connection, None)
```
So I wonder, zerorpc can only expose objects that only have methods. 
If that is the case I know that I can wrap my object in other that only has the methods so zerorpc can work. 
Want to know what is common practice in zerorpc.

**Comment by bombela** [comment]
zerorpc exposes a bunch of functions. For convenience, you can provide an object to zerorpc, which is then going to expose every methods of it.
