### ISSUE TITLE
dependency (==) on pyzmq

### ISSUE THREAD

**Issue by wiggin15** [0rpc/zerorpc-python#77]
ZeroRPC 0.4.4 depends on pyzmq==13.1.0. Python/setuptools don't handle "==" dependencies well - if a project depends on both pyzmq and zerorpc, and setuptools decides to download pyzmq first, it will install the newest pyzmq, and then fail when it reaches the installation of zerorpc...
I understand that the newest pyzmq breaks zerorpc, but I'm not sure what's the problem. Is it possible to adapt zerorpc and/or open an issue for pyzmq to fix their issues?

**Comment by bombela** [comment]
>= in v5.0.1 on pypi. I do prefer >= instead of == for libraries.
