### ISSUE TITLE
Dynamically change the init class ?

### ISSUE THREAD

**Issue by LeHibou** [0rpc/zerorpc-python#81]
Hello, in your example :
*******************************************************************************************************
/*Python server*/
s = zerorpc.Server(HelloRPC())
s.bind("tcp://0.0.0.0:4242")
s.run()
*******************************************************************************************************
Could we have say two classes in the server code ? :
*******************************************************************************************************
/*Idea for python server*/
import zerorpc

class HelloRPC(object):
    def hello(self, name):
        return "Hello, %s" % name

class HelloRPC2(object):
    def hello(self, name):
        return "Hello, %s" % name

s = zerorpc.Server()
s.bind("tcp://0.0.0.0:4242")
s.run()
*******************************************************************************************************
and choose dynamically which class to execute thanks to a parameter sent by the client  ?
*******************************************************************************************************
/*Python Client*/
import zerorpc

c = zerorpc.Client()
c.connect("tcp://127.0.0.1:4242")
print c.HelloRPC2.hello("RPC")
*******************************************************************************************************
Same question for nodejs..

Thanks !

**Comment by bombela** [comment]
The subrpc branch is dead now. I still hope to build something like that one day though. Having transactions can be useful.
