### ISSUE TITLE
Please update the pypi package

### ISSUE THREAD

**Issue by medecau** [0rpc/zerorpc-python#82]
I spent most part of the last two days trying to figure out why the Publisher/Subscriber pattern wasn't working.

After running pip install -I <the github zip> it worked on the first run.

**Comment by snth** [comment]
It looks like 3056243b942d14dd62c6e8ae0d9e7847b3999298 unpinned the pyzmq requirement so could you please publish an updated pypi package that incorporates this? Having the pyzmq==13.1.0 requirement in the latest pypi version still causes many problems with other packages that require pyzmq>=14.0.0.

**Comment by snth** [comment]
It seems like this has been resolved in the latest master. If you could roll that out in a release to close #82 then you could probably also close this issue.

**Comment by bombela** [comment]
Thanks for the ping, will do it this afternoon.

**Comment by bombela** [comment]
0.5.1 on pypi -> https://pypi.python.org/pypi/zerorpc

**Comment by snth** [comment]
Thanks
