### ISSUE TITLE
How keep alive a client?

### ISSUE THREAD

**Issue by mamcx** [0rpc/zerorpc-python#95]
I'm building a service that (crons) that could take hours/day before activate a client. So for the majority of the time, the client(s) will be waiting for a job.

How can I keep alive the client, and still get new task for a server when ready?

Think in something like pubnub.com

**Comment by theY4Kman** [comment]
I think I'm facing the same issue. Could you shine any more light on it?

**Comment by fordoo** [comment]
@Carbaz @mauricioabreu  gevent will not switch greenlet in long loop(no i/o wait) before you use 'gevent.sleep(0)'.
Mybay you can use code below instead.

    def slowmethod(self):
        for x in range(20000):#This is, aprox, the time in ms (on my old I7)
            if x%100 == 0:
                print ("x: {}".format(x))
            for n in range(10000):
                y = x*x
            gevent.sleep(0)
        return 'Slow Done'

**Comment by Carbaz** [comment]
Hi @fordoo, I can not change code of executed methods as they are arbitrary and not have direct control over them. I saw greenlets can not handle that kind of concurrence (arbitrary code) so

Is there a version of zeroRPC with threads instead of greenlets?

**Comment by bombela** [comment]
Nope, there is no version with threads. Also, to solve this problem and also make it easier to support more IO style and more languages, I do have plans to move the core of zerorpc to its own compiled lib, with threads in order to be independent. Very much like how zmq does it.
