### ISSUE TITLE
msgpack can not pack my custom class

### ISSUE THREAD

**Issue by ceremcem** [0rpc/zerorpc-python#98]
Hi, 

I tried to switch to Pyro4 with zerorpc but one of my custom class instance can not be packed by msgpack. Here is the issue link: https://github.com/msgpack/msgpack-python/issues/96

Could we tell zerorpc to use pickle instead of msgpack?

**Comment by pixelbombs** [comment]
@mauricioabreu So we use msgpack to serialize our custom classes. How do we implement this into zerorpc? Like @bombela said, this is implementing our own serialization layer (and he advices against it). I'm trying to use zerorpc with dockerpy and it's not gonna work because we can't serialize the Docker client class with msgpack.

**Comment by bombela** [comment]
You can absolutely implement your own serialization layer. I am not advising against it at all.

I wasn't clear enough, I am against using picke to serialize code to send it across the network. This sounds dangerous to me.

I don't think we can easily allow the integration of msgpack user defined type in zerorpc, and here's few reason why:

 - zerorpc is language agnostic.
 - zerorpc command line expect to be able to introspect everything, independent of the language used on the server.
 - zerorpc supports the notion of proxy, including proxy that are able to rewrite the serialization used (think for example, of a zerorpc proxy between websocket & json to/from zmq & msgpack.
 - zerorpc is not tied to msgpack.
 - zerorpc limits itself to json-like datatype for the above reasons.

To restate, you can absolutely serialize via msgpack with your custom type onto some binary blob that you then pass-trough zerorpc.

Now, for the technical bits and performances; I am pretty sure that adding another layer of serialization wont affect much. We are in python after all, everything is already slow ;)

**Comment by pixelbombs** [comment]
@bombela Oh okay, sweet! Thanks for the hasty response man.
